### ISSUE TITLE
Custom sounds for friends play for everyone instead of only for favorited friends.

### ISSUE THREAD

**Issue by spectrapulse** [Nevvulo/betterfriends#10]
When setting a notification sound for friends it will play for every notification I get.

It also plays it in Settings > Notifications > Notification Sound and it seems to just replace the sound entirely.

If this is by design, this is misdocumented.

**Comment by Nevvulo** [comment]
This is a known bug, the "custom sounds" feature wasn't fully completed when I implemented it, at first it was mainly being used as a test to see if I could actually replace the sounds in the first place. I'm going to attempt to try and make this feature work properly - in the event that I can't for some reason, I'll update the documentation. Thanks!

**Comment by Nevvulo** [comment]
Fixed in 959d6f
