### ISSUE TITLE
Sound for receiving calls doesn't actually play when recieving a call.

### ISSUE THREAD

**Issue by spectrapulse** [Nevvulo/betterfriends#11]
Like the title says, it plays the sound in Settings > Notifications > Incoming Calls and Settings > Better Friends > Incoming Call but it doesn't actually play on recieving a call.

**Comment by Nevvulo** [comment]
I've made substantial changes to the way the notification sound system works and I believe this issue doesn't occur anymore, however please re-open if it does 👍
