### ISSUE TITLE
Favorite Friends Erroring

### ISSUE THREAD

**Issue by DracoClaw** [Nevvulo/betterfriends#29]
I tried to right click on a Favorite Friend from my list who I have not interacted with in DM for some time, since May 10 2020, and it crashed. Left clicking the user brought up a loading screen that did not go away. The only fix was to search for the user and open the dm through the search area.

**Comment by Juby210** [comment]
i have no idea what do you mean, i tested on someone with last message more than year ago on DMs and i can open DM normally.
