### ISSUE TITLE
No Invite to Spotify Option

### ISSUE THREAD

**Issue by DracoClaw** [Nevvulo/betterfriends#30]
While pc-spotify integration is advertised, I am not getting the option to invite a friend. 
![image](https://user-images.githubusercontent.com/34274162/90399633-eedd6800-e0a3-11ea-9485-3277edfced59.png)

**Comment by Juby210** [comment]
It isn't invite option. It's listen to along option - if your friends are listening to spotify you will see it in context menu and you can easily join to party.

**Comment by DracoClaw** [comment]
oh i misunderstood, would that be an option to add?

**Comment by Juby210** [comment]
it can be
