### ISSUE TITLE
Favorite Friends List Scrollbar Bug

### ISSUE THREAD

**Issue by fawni** [Nevvulo/betterfriends#33]
Can't scroll past favorite friends list _(at least not smoothly)_ unless it's collapsed.
<details>
  <summary>Gif Example</summary>
  
 ![23_12_2020-15_50_ZOZ4I0Y2](https://user-images.githubusercontent.com/36301891/103003328-42bbfa00-4539-11eb-99c4-c2012713d0b4.gif)
</details>

**Comment by rnbr04** [comment]
Happens with me too

**Comment by sp96296** [comment]
is there a reason this issue was closed? I am still having the scroll problem.

**Comment by fawni** [comment]
> is there a reason this issue was closed? I am still having the scroll problem.

the issue has been created 7 months ago with no replies and the dev doesn't maintain this plugin anymore
