### ISSUE TITLE
How do I run/install this?

### ISSUE THREAD

**Issue by mohitkyadav** [Nevvulo/betterfriends#4]

**Comment by Nevvulo** [comment]
I'll make sure to include instructions in the README, but essentially:

Provided you have installed and injected Powercord correctly (see [here](https://github.com/powercord-org/powercord/wiki/Installation) for instructions)
`1.` Clone the repo into your Powercord plugins folder (found in `powercord/src/Powercord/plugins`)
`2.` CTRL+R in your canary client to restart.

Done! The plugin should be installed. You can start adding favorited friends in the [Settings menu](https://massive-legend.nevulo.xyz/mS7LxinF.png), or by right clicking friends and clicking "Add as Favorite"

**Comment by mohitkyadav** [comment]
thanks @Nevvulo
