### ISSUE TITLE
I only get the settings option.

### ISSUE THREAD

**Issue by Eldryuu** [Nevvulo/betterfriends#7]
Better Friends is under PowerCord in the settings and I can set who is my favorite friends and all that, but when I've selected some friends nothing really happens, no one gets a star, I don't get the list for favorite friends and I can't right click on anyone and set them as a favorite friend through there.

**Comment by Nevvulo** [comment]
My apologies for the late reply, but could you try pulling from `master` and trying again? I've made major improvements to the plugin over the past few days after a few weeks of inactivity, and the plugin may have been stale due to Discord updates and such.

**Comment by Nevvulo** [comment]
Closing due to to inactivity, please let me know if this is still an issue on the latest `master` branch
